config/routes.rb
Rails.application.routes.draw do
  resources :events
  get "welcome/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
  get "/auth/:provider/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, "は終了時間よりも前に設定してください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: "Event", foreign_key: "owner_id"

  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by!(provider:, uid:) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  before_action :authenticate
  helper_method :logged_in?, :current_user
  allow_browser versions: :modern
  layout "application"

  private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: "ログインしてください"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: "を作成しました"
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :content, :start_at, :end_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: :create

  def create
    user = User.find_or_create_from_auth_hash!(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, notice: "ログインしました"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
  end
end

app/views/application/_errors.htnl.haml
.alert.alert-danger
  %ul.mb-0
    - errors.full_message.each do |message|
      %li= message

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

app/views/events/new.html.haml
- now = Time.zone.now

%h1.mt-2 イベント作成

= form_with(model: @event, class: "form-horizontal") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_field :content, class: "form-control", row: 10
  = f.submit class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %title Awesome Events
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %header.navbar.navbar-expand-sm.navbar-light.bg-light
      .container
        = link_to "AwesomeEvents", root_path, class: "navbar-brand mr-auto"
        %ul.navbar-nav
          %li.nav-item
            = link_to "イベントを作る", new_event_path, class: "nav-link"
          - if logged_in?
            %li.nav-item
              = button_to "ログアウト", logout_path, method: :delete, class: "nav-link"
          - else
            %li.nav-item
              = button_to "Githubでログイン", "/auth/github", class: "nav-link", data: { turbo: false }
    .container
      - if flash.notice
        .alert.alert-success
          = flash.notice
      - if flash.notice
        .alert.alert-danger
          = flash.alert
      = yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>